//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbfinalprojectEntities : DbContext
    {
        public dbfinalprojectEntities()
            : base("name=dbfinalprojectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<p_articles> p_articles { get; set; }
        public virtual DbSet<p_author> p_author { get; set; }
        public virtual DbSet<p_author_articles> p_author_articles { get; set; }
        public virtual DbSet<p_customer> p_customer { get; set; }
        public virtual DbSet<p_emp_expense> p_emp_expense { get; set; }
        public virtual DbSet<p_employee> p_employee { get; set; }
        public virtual DbSet<p_expense_cat> p_expense_cat { get; set; }
        public virtual DbSet<p_items> p_items { get; set; }
        public virtual DbSet<p_magazine> p_magazine { get; set; }
        public virtual DbSet<p_other_expense> p_other_expense { get; set; }
        public virtual DbSet<p_publication> p_publication { get; set; }
        public virtual DbSet<p_purchase> p_purchase { get; set; }
        public virtual DbSet<p_transaction> p_transaction { get; set; }
    }
}
