//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbproject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class p_articles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_articles()
        {
            this.p_author_articles = new HashSet<p_author_articles>();
        }
        [DisplayName("Article ID")]
        public int article_id { get; set; }
        [DisplayName("Title")]
        public string title { get; set; }
        [DisplayName("Page No")]
        public string page_no { get; set; }
        [DisplayName("Publication ID")]
        public Nullable<int> publication_id { get; set; }

        public virtual p_publication p_publication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_author_articles> p_author_articles { get; set; }
    }
}
