//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_other_expense
    {
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<float> cost { get; set; }
        public int category_id { get; set; }
    
        public virtual p_expense_cat p_expense_cat { get; set; }
    }
}
